### ISSUE TITLE
Support for three-digit version numbers?

### ISSUE THREAD

**Issue by nicograef** [WhichBrowser/Parser-JavaScript#61]
Chrome and Firefox will soon reach version 100.

This article describes how this might break libraries that parse the user-agent:
https://hacks.mozilla.org/2022/02/version-100-in-chrome-and-firefox/

Additionally, it seems that Chromium 100 brings even more changes to the user-agent string:
https://www.xda-developers.com/chrome-100-beta/

I have not seen any issues, prs or release notes of the `which-browser` package that are related to this issue.

Is the current version of `which-browser` forward compatible with three-digit browser version numbers?

**Comment by mariotsi** [comment]
Hey,
I tested both UserAgents, plus the one from Chrome Stable since the v100 came out.

The version number was detected correctly but in Chrome there was an issue that led the camouflage flag to be added and the string outcome was `an unknown browser that imitates Chrome 110 on Windows 10`

I did fix the camouflage issue and added the stable versions of Chrome 99 and 100 in #62 

Upgrade and you'll be good to go with the three digit browsers versions.

Simone
